#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch post.foam

rm -rf constant/polyMesh

surfaceFeatureEdges cadouter.stl cadouter.fms
cartesianMesh

runApplication topoSet

restore0Dir

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar -latestTime