#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runParallel $(getApplication)

# Optional: reconstruct latest time after parallel run
# runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
